### ISSUE TITLE
FileLogger Directory Confusion

### ISSUE THREAD

**Issue by laughin1** [lolp1/MemorySharp#4]
When creating a FileLogger it requires a FileLoggerParams where a FileName & Directory is defined.

It is confusing for the FileName to be used in the directory path of the log file.
{Directory}/{FileName}-{Date}.txt

This can lead to errors because on FileLogger.cs:29 you create a directory and then try and open a StreamWriter in a sub-directory which might exist.

I reccomend you switch to the following format:
{Directory}/{FileName}-{Date}.txt

**Comment by lolp1** [comment]
Merged the fix, hope it solves it thanks.
