### ISSUE TITLE
mono_domain_get returns null

### ISSUE THREAD

**Issue by bbday** [lolp1/MemorySharp#6]
https://github.com/UnityInjector/Uni...m.cs#L157-L160

so I am trying to use this project to inject dll, keep getting
mono_domain_get returned 0 (0x00)

everything starts ok and it finds the mono_domain_get function
but when calling it. it says it returns null.

I opened up CE and placed breakpoint on that function
Code:

>     mono.mono_domain_get - push [mono.dll+1F305C] { [0000002A] }
>     mono.mono_domain_get+6- call dword ptr [mono.dll+131180] { ->kernel32.TlsGetValue }
>     mono.mono_domain_get+C- ret

after this call eax is 03544E70 I believe this is the right result? (this result comes back every time after execution)

so why does MemorySharp says it returns null?

http://www.unknowncheats.me/forum/c-/179138-mono-memorysharp-mono_domain_get-returns-null.html

**Comment by lolp1** [comment]
Please use this project I wrote instead, it serves at a replacement and I no longer support this one.

https://github.com/lolp1/Process.NET

:) Thanks for checking the lib out.
